apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  DB: {{ .Values.db.DB | b64enc }}
  DB_USER: {{ .Values.db.DB_USER | b64enc }}
  DB_PASSWORD: {{ .Values.db.DB_PASSWORD | b64enc }}
  DB_HOST: {{ .Values.db.DB_HOST | b64enc }}